#!/usr/bin/perl
# $Id: mkst,v 1.5 2016-10-26 13:49:08-07 - - $
# Run smalltalk and capture the output.

$0 =~ s|.*/||;
$prog = $ARGV[0];
$lis = "$prog.lis";

open PROG, "<$prog" or die "$0: $prog: $!";
open LIS, ">$lis" or die "$0: $prog: $!";

while (<PROG>) {
   next unless m/"TEST:\s*(.*)"/;
   $cmd = $1;
   print LIS ":" x 32, "\n", "$0: $cmd\n", ":" x 32, "\n";
   print LIS `$cmd`;
   print LIS "::::::::::Exit status $?\n";
}

system "mkpspdf $prog.ps $prog $lis";

